server:
  port: 8907
  servlet:
    context-path: /event
spring:
  application:
    name: event-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/it_mob_event
    username: user
    password: pass
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: validate
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: true
    flyway:
      enabled: true


