version: '3.8'

volumes:
  postgres_nya:
    driver: local

services:

  it_mob_event-db:
    image: library/postgres:latest
    container_name: it_mob_event
    volumes:
      - type: volume
        target: /var/lib/postgresql
    environment:
      POSTGRES_DB: it_mob_event
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10

  it_mob_front-db:
    image: library/postgres:latest
    container_name: it_mob_front
    volumes:
      - type: volume
        target: /var/lib/postgresql
    environment:
      POSTGRES_DB: it_mob_front
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10

  it_mob_p-db:
    image: library/postgres:latest
    container_name: it_mob_pm
    volumes:
      - type: volume
        target: /var/lib/postgresql
    environment:
      POSTGRES_DB: it_mob_pm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10

  it_mob_user-db:
    image: library/postgres:latest
    container_name: it_mob_user
    volumes:
      - type: volume
        target: /var/lib/postgresql
    environment:
      POSTGRES_DB: it_mob_user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10

  events-service:
    build:
      context: ./events-service
    ports:
      - "8907:8907"
    depends_on:
      it_mob_event-db:
        condition: service_healthy

  front-service:
    build:
      context: ./front-service
    ports:
      - "8191:8191"
    depends_on:
      it_mob_front-db:
        condition: service_healthy

  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "80:80"

  user-service:
    build:
      context: ./user-service
    ports:
      - "9001:9001"
    depends_on:
      it_mob_user-db:
        condition: service_healthy