server:
  port: 9090

spring:
  application:
    name: pm-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/it_mob_pm
    username: user
    password: pass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  flyway:
    enabled: true

security:
  token:
    expiration:
      days: 30
    secret:
      key: secret-key
