server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8191"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: user-service
#          uri: http://localhost:9001
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>.*), /$\{segment}
            - JwtTokenFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/


security:
  token:
    secret:
      key: secret-key