server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

security:
  token:
    expiration:
      days: 30
    secret:
      key: secret-key
