server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/it_mob_user
    username: user
    password: pass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

security:
  token:
    expiration:
      days: 30
    secret:
      key: secret-key
